services:
    web: &web
        build: .
        image: web
        #pull_policy: always
        ports:
            - '${APP_PORT:-80}:80'
            - '${APP_PORT_HTTPS:-443}:443'
        volumes:
            #- ./src:/var/www/html # uncomment this if you want to use src folder inside running container, development use
            - 'ide21src:/var/www/html' #otherwise use named volume, for production use
        #user: ${CURRENT_UID}
        command: /bin/bash -c "/var/www/html/startup.sh"
        networks:
            - cmside2
        depends_on:
            - mysqldb
    mysqldb:
        image: 'mariadb:10.9.4'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./data:/var/lib/mysql
            #- '${MYSQL_DATA_PATH:-./data}:/var/lib/mysql'
        networks:
            - cmside2
networks:
    cmside2:
        driver: bridge
volumes:
    ide21src:
        driver: local
    data:
        driver: local
